name: Rạng Đông Key Helper
version: "0.1.0"
slug: rangdong_key_helper
description: Nhập local key từ điện thoại Android đã root của bạn qua ADB và Frida
url: https://github.com/trankhanhduy2929-beep/rangdong-homeassistant/tree/main/rangdong_key_helper
image: ghcr.io/trankhanhduy2929-beep/rangdong-key-helper
arch:
  - aarch64
  - amd64
homeassistant: "2026.8.0"
boot: manual
stage: experimental
ingress: true
panel_icon: mdi:key-wireless
panel_title: Khóa Rạng Đông
homeassistant_api: true
options:
  adb_port: 5555
  package_name: com.rd.smart
schema:
  android_host: str?
  adb_port: port
  package_name: str
